/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from "./lib";
export type { lib };
export type { FavoriteNumber } from "./FavoriteNumber";
export * as factories from "./factories";
export { FavoriteNumber__factory } from "./factories/FavoriteNumber__factory";
export type { ExtendedOperations } from "./lib/MpcInterface.sol/ExtendedOperations";
export { ExtendedOperations__factory } from "./factories/lib/MpcInterface.sol/ExtendedOperations__factory";
